// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cdtVU2aoa983eSNLcnPTCH
// Component: hSfSvIyAAK

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { Embed } from "@plasmicpkgs/plasmic-basic-components"; // plasmic-import: PKldDYkH42/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_devopsick_com.module.css"; // plasmic-import: cdtVU2aoa983eSNLcnPTCH/projectcss
import sty from "./PlasmicStarsBackend2.module.css"; // plasmic-import: hSfSvIyAAK/css

export type PlasmicStarsBackend2__VariantMembers = {};
export type PlasmicStarsBackend2__VariantsArgs = {};
type VariantPropType = keyof PlasmicStarsBackend2__VariantsArgs;
export const PlasmicStarsBackend2__VariantProps = new Array<VariantPropType>();

export type PlasmicStarsBackend2__ArgsType = {};
type ArgPropType = keyof PlasmicStarsBackend2__ArgsType;
export const PlasmicStarsBackend2__ArgProps = new Array<ArgPropType>();

export type PlasmicStarsBackend2__OverridesType = {
  root?: p.Flex<typeof Embed>;
};

export interface DefaultStarsBackend2Props {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicStarsBackend2__RenderFunc(props: {
  variants: PlasmicStarsBackend2__VariantsArgs;
  args: PlasmicStarsBackend2__ArgsType;
  overrides: PlasmicStarsBackend2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <Embed
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
      code={
        '<div id="stars5"></div>\r\n<div id="stars6"></div>\r\n<div id="stars7"></div>' as const
      }
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStarsBackend2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStarsBackend2__VariantsArgs;
    args?: PlasmicStarsBackend2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStarsBackend2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicStarsBackend2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicStarsBackend2__ArgProps,
          internalVariantPropNames: PlasmicStarsBackend2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStarsBackend2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStarsBackend2";
  } else {
    func.displayName = `PlasmicStarsBackend2.${nodeName}`;
  }
  return func;
}

export const PlasmicStarsBackend2 = Object.assign(
  // Top-level PlasmicStarsBackend2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicStarsBackend2
    internalVariantProps: PlasmicStarsBackend2__VariantProps,
    internalArgProps: PlasmicStarsBackend2__ArgProps
  }
);

export default PlasmicStarsBackend2;
/* prettier-ignore-end */
